MODEL:
  TYPE: vssm
  NAME: vssm1_svmamba
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 128
    DEPTHS: [ 3, 3, 4, 3 ]
    SSM_D_STATE: 16
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v2"
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
